
$catalog = @(
    "https://research.google/blog/rss/",
    "https://www.microsoft.com/en-us/research/feed/",
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    "https://openai.com/blog/rss.xml",
    "https://www.anthropic.com/blog/rss.xml",
    "https://venturebeat.com/category/ai/feed/",
    "https://blog.google/technology/ai/rss/",
    "https://blog.google/technology/google-deepmind/rss/",
    "https://aws.amazon.com/blogs/machine-learning/feed/",
    "https://github.blog/ai-and-ml/feed/",
    "https://huggingface.co/blog/feed.xml",
    "https://blogs.nvidia.com/feed/",
    "https://hnrss.org/frontpage?q=AI&points=50",
    "https://www.reddit.com/r/artificial/.rss",
    "https://www.engadget.com/rss.xml",
    "https://9to5google.com/guides/google/feed/",
    "https://www.androidauthority.com/feed/",
    "https://www.techradar.com/rss",
    "https://www.zdnet.com/news/rss.xml",
    "https://www.bleepingcomputer.com/feed/",
    "https://techcrunch.com/feed/",
    "https://www.theverge.com/rss/index.xml",
    "https://feeds.arstechnica.com/arstechnica/index",
    "https://www.wired.com/feed/rss",
    "https://9to5mac.com/guides/apple/feed/",
    "https://feeds.macrumors.com/MacRumors-All",
    "https://hnrss.org/frontpage?points=100",
    "https://www.producthunt.com/feed",
    "https://techsauce.co/feed",
    "https://www.beartai.com/feed",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://feeds.reuters.com/reuters/technologyNews",
    "http://rss.cnn.com/rss/cnn_tech.rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "https://www.theguardian.com/technology/rss",
    "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=100003661",
    "https://feeds.bloomberg.com/technology/news.rss",
    "https://blog.cloudflare.com/rss/",
    "https://www.docker.com/blog/feed/",
    "https://github.blog/engineering/feed/",
    "https://feed.infoq.com/",
    "https://stackoverflow.blog/feed/",
    "https://thenewstack.io/feed/",
    "https://www.darkreading.com/rss.xml",
    "https://www.securityweek.com/feed/",
    "https://therecord.media/feed",
    "https://www.schneier.com/feed/atom/",
    "https://krebsonsecurity.com/feed/",
    "https://techcrunch.com/category/security/feed/",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.eurogamer.net/feed",
    "https://www.polygon.com/rss/index.xml",
    "https://www.pcgamer.com/rss/",
    "https://www.gamespot.com/feeds/news/",
    "https://feeds.feedburner.com/ign/all",
    "https://kotaku.com/rss",
    "https://feeds.arstechnica.com/arstechnica/gaming",
    "https://www.theguardian.com/games/rss",
    "https://www.reddit.com/r/gaming/top/.rss?t=day",
    "https://www.compgamer.com/feed/",
    "https://cointelegraph.com/rss",
    "https://decrypt.co/feed",
    "https://www.coindesk.com/arc/outboundfeeds/rss/",
    "https://www.theblock.co/rss.xml",
    "https://cryptoslate.com/feed/",
    "https://techcrunch.com/category/cryptocurrency/feed/",
    "https://www.reddit.com/r/cryptocurrency/top/.rss?t=day",
    "https://fortune.com/feed/",
    "https://www.fastcompany.com/rss",
    "https://www.inc.com/rss/homepage.xml",
    "https://www.economist.com/latest/rss.xml",
    "https://hbr.org/stories.rss",
    "http://feeds.bbci.co.uk/news/business/rss.xml",
    "https://feeds.reuters.com/reuters/businessNews",
    "http://rss.cnn.com/rss/money_latest.rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    "https://techcrunch.com/category/startups/feed/",
    "https://www.theguardian.com/business/rss",
    "https://www.wired.com/feed/category/business/latest/rss",
    "https://brandinside.asia/feed/",
    "https://www.prachachat.net/feed",
    "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    "https://seekingalpha.com/feed.xml",
    "https://feeds.bloomberg.com/markets/news.rss",
    "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=100006641",
    "https://finance.yahoo.com/news/rssindex",
    "https://www.reddit.com/r/investing/top/.rss?t=day",
    "https://www.nasa.gov/rss/dyn/breaking_news.rss",
    "https://www.quantamagazine.org/feed/",
    "https://www.sciencenews.org/feed",
    "https://www.livescience.com/feeds/all",
    "https://www.nature.com/nature.rss",
    "https://www.newscientist.com/feed/home/",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "https://feeds.reuters.com/reuters/scienceNews",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "https://www.theguardian.com/science/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.reddit.com/r/science/top/.rss?t=day",
    "http://rss.cnn.com/rss/cnn_topstories.rss",
    "http://rss.cnn.com/rss/cnn_world.rss",
    "https://feeds.bbci.co.uk/news/rss.xml",
    "https://feeds.reuters.com/reuters/topNews",
    "https://feeds.apnews.com/rss/apf-topnews",
    "https://feeds.npr.org/1001/rss.xml",
    "https://www.aljazeera.com/xml/rss/all.xml",
    "https://www.theguardian.com/world/rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "https://abcnews.go.com/abcnews/topstories",
    "https://www.cbsnews.com/latest/rss/main",
    "https://feeds.washingtonpost.com/rss/world",
    "https://feeds.bloomberg.com/politics/news.rss",
    "https://time.com/feed/",
    "https://www.ft.com/?format=rss",
    "https://www.bangkokpost.com/rss/data/topstories.xml",
    "https://thestandard.co/feed/",
    "https://thematter.co/feed",
    "https://www.matichon.co.th/feed",
    "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "https://feeds.reuters.com/Reuters/PoliticsNews",
    "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
    "http://rss.cnn.com/rss/cnn_allpolitics.rss",
    "http://feeds.bbci.co.uk/news/health/rss.xml",
    "https://feeds.reuters.com/reuters/healthNews",
    "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    "http://rss.cnn.com/rss/cnn_health.rss",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    "https://feeds.reuters.com/reuters/entertainment",
    "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    "http://rss.cnn.com/rss/edition_entertainment.rss",
    "http://feeds.bbci.co.uk/sport/rss.xml",
    "https://feeds.reuters.com/reuters/sportsNews",
    "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml",
    "http://rss.cnn.com/rss/edition_travel.rss",
    "https://www.theguardian.com/travel/rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "https://www.theguardian.com/lifeandstyle/rss",
    "https://feeds.reuters.com/reuters/lifestyle",
    "https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml",
    "https://www.theguardian.com/food/rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml",
    "https://www.theguardian.com/environment/rss",
    "https://feeds.reuters.com/reuters/environment",
    "https://rss.nytimes.com/services/xml/rss/nyt/Education.xml",
    "http://feeds.bbci.co.uk/news/family_and_education/rss.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml",
    "https://www.theguardian.com/commentisfree/rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml",
    "https://www.autoblog.com/rss.xml"
)

$headers = @{
    "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
    "Accept" = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
    "Referer" = "https://www.google.com/"
}

foreach ($url in $catalog) {
    try {
        $resp = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -TimeoutSec 10 -ErrorAction Stop
        $content = $resp.Content.Trim()
        
        if ($content -match "^<!DOCTYPE html" -or $content -match "^<html") {
            Write-Host "BLOCK: $url (Returns HTML)" -ForegroundColor Red
        } elseif ($content -match "^<\?xml") {
            # Success
        } elseif ($content -match "^<rss") {
            # Success
        } elseif ($content -match "^<feed") {
            # Success (Atom)
        } else {
            Write-Host "UNKNOWN: $url (Starts with: $($content.Substring(0, [Math]::Min(20, $content.Length))))" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "FAIL: $url ($($_.Exception.Message))" -ForegroundColor Magenta
    }
}
