import { getSummaryDateLabel } from '../../utils/summaryDates';

type CreateHomeWorkspaceArgs = Record<string, any>;

export const createHomeWorkspaceProps = ({
  activeFilterPrompt,
  activeFilters,
  activeListId,
  aiFilterBrief,
  aiFilterSummary,
  bookmarkIdSet,
  canLoadMoreFeed,
  clearAiFilter,
  currentActiveList,
  deletedFeedCount,
  feed,
  freshFeedIds,
  handleAiFilter,
  handleBookmark,
  handleDeleteAll,
  handlePlanLoadMore,
  handlePlanSync,
  handleSort,
  handleUndo,
  hasReachedFeedCardLimit,
  homeFeedCardLimit,
  isFiltered,
  isFeedHistoryHydrated,
  isFilterPrimed,
  isFiltering,
  isLoadingMore,
  isSyncing,
  loading,
  openArticleReader,
  openContentComposerFromPost,
  originalFeed,
  postLists,
  setFilterModal,
  setIsMobilePostListOpen,
  setStatus,
  visibleFeedTotalCount,
  visibleQuickPresets,
  watchlistHandleSet,
}: CreateHomeWorkspaceArgs) => ({
  currentActiveList,
  activeListId,
  originalFeedLength: originalFeed.length,
  deletedFeedLength: deletedFeedCount,
  feed,
  freshFeedIds,
  activeFilterPrompt,
  isFiltered,
  isFeedHistoryHydrated,
  activeFilters,
  visibleQuickPresets,
  isFilterPrimed,
  isFiltering,
  isLoadingMore,
  isSyncing,
  hasReachedFeedCardLimit,
  homeFeedCardLimit,
  loading,
  visibleFeedTotalCount,
  canLoadMoreFeed,
  aiFilterBrief,
  aiFilterSummary,
  aiFilterSummaryDateLabel: getSummaryDateLabel(feed, 8),
  bookmarkIdSet,
  watchlistHandleSet,
  postLists,
  onOpenMobileList: () => setIsMobilePostListOpen(true),
  onDeleteAll: handleDeleteAll,
  onUndo: handleUndo,
  onSort: handleSort,
  onQuickFilter: handleAiFilter,
  onOpenFilterModal: () => setFilterModal({ show: true, prompt: '' }),
  onSync: handlePlanSync,
  onLoadMore: handlePlanLoadMore,
  onClearAiFilter: clearAiFilter,
  onBookmark: handleBookmark,
  onArticleGen: openContentComposerFromPost,
  onReadArticle: openArticleReader,
  onSummaryCopied: () => setStatus('คัดลอกผลลัพธ์จาก FORO Filter แล้ว'),
});

export type HomeWorkspaceContract = ReturnType<typeof createHomeWorkspaceProps>;
