import {
  dispatchProfileSectionChange,
  PROFILE_SECTION_EVENT,
  READ_ARCHIVE_RENDER_BATCH,
} from './constants';
import { createHomeWorkspaceProps } from '../features/home/createHomeWorkspaceProps';

type WorkspaceRouterBuilderArgs = Record<string, any>;

export const createWorkspaceRouterProps = (args: WorkspaceRouterBuilderArgs) => {
  const {
    activeListId,
    activePlanId,
    activeSearchFocus,
    activeFilterPrompt,
    activeFilters,
    aiFilterBrief,
    aiFilterSummary,
    aiQuery,
    aiSearchError,
    aiSearchHasMore,
    aiSearchLoading,
    aiSearchResults,
    audienceTab,
    bookmarkIds,
    bookmarkIdSet,
    bookmarkTab,
    canLoadMoreFeed,
    canSaveCurrentSearchAsPreset,
    contentTab,
    createContentSource,
    currentActiveList,
    currentPlan,
    dailyUsage,
    deletedFeedCount,
    dismissSearchChoices,
    dynamicSearchTags,
    feed,
    filteredBookmarks,
    filteredReadArchive,
    freshFeedIds,
    genPhase,
    handleAddExpert,
    handleAddSearchAuthorToWatchlist,
    handleAiFilter,
    handleAiSearchAudience,
    handleBeforeGenerate,
    handleBeforeRegenerate,
    handleBookmark,
    handleDeleteAll,
    handleManualSearch,
    handlePlanLoadMore,
    handlePlanSearch,
    handlePlanSelection,
    handlePlanSync,
    handleRemoveAccountGlobal,
    handleSaveGeneratedArticle,
    handleSort,
    handleToggleMemberInList,
    handleToggleSource,
    handleUndo,
    hasReachedFeedCardLimit,
    hasSearchedAudience,
    homeFeedCardLimit,
    interestSeedLabels,
    isFiltered,
    isFiltering,
    isGeneratingContent,
    isLatestMode,
    isLiveSearching,
    isLoadingMore,
    isSearching,
    isSourcesExpanded,
    isStartingCheckout,
    isSyncing,
    loading,
    manualPreview,
    manualQuery,
    openArticleReader,
    openContentComposerFromPost,
    originalFeed,
    plusAccess,
    postLists,
    readArchive,
    readFilters,
    readSearchQuery,
    readSearchSuggestions,
    remainingUsage,
    removeSearchPreset,
    searchChoiceOptions,
    searchCursor,
    searchHistory,
    searchMediaType,
    searchOverflowResults,
    searchPresets,
    searchQuery,
    searchResults,
    searchStatusMessage,
    searchSummary,
    searchWebSources,
    setActiveSuggestionIndex,
    setAiQuery,
    setAiSearchResults,
    setAudienceTab,
    setBookmarkTab,
    setBookmarks,
    setContentTab,
    setCreateContentSource,
    setFilterModal,
    setGenPhase,
    setIsGeneratingContent,
    setIsLatestMode,
    setIsMobilePostListOpen,
    setIsSourcesExpanded,
    setManualQuery,
    setMobileProfileSection,
    setReadFilters,
    setReadSearchQuery,
    setSearchCursor,
    setSearchMediaType,
    setSearchOverflowResults,
    setSearchQuery,
    setSearchResults,
    setSearchSummary,
    setSearchWebSources,
    setShowSuggestions,
    setStatus,
    setVisibleReadCount,
    shouldInlineSearchStatus,
    shouldShowSearchChoices,
    showSuggestions,
    subscribedSources,
    suggestions,
    visibleQuickPresets,
    visibleReadArchive,
    watchlist,
    watchlistHandleSet,
    setActiveView,
  } = args;

  return {
    home: createHomeWorkspaceProps({
      activeFilterPrompt,
      activeFilters,
      activeListId,
      aiFilterBrief,
      aiFilterSummary,
      bookmarkIdSet,
      canLoadMoreFeed,
      clearAiFilter: args.clearAiFilter,
      currentActiveList,
      deletedFeedCount,
      feed,
      freshFeedIds,
      handleAiFilter,
      handleBookmark,
      handleDeleteAll,
      handlePlanLoadMore,
      handlePlanSync,
      handleSort,
      handleUndo,
      hasReachedFeedCardLimit,
      homeFeedCardLimit,
      isFiltered,
      isFilterPrimed: args.isFilterPrimed,
      isFiltering,
      isLoadingMore,
      isSyncing,
      loading,
      openArticleReader,
      openContentComposerFromPost,
      originalFeed,
      postLists,
      setFilterModal,
      setIsMobilePostListOpen,
      setStatus,
      visibleFeedTotalCount: args.visibleFeedTotalCount,
      visibleQuickPresets,
      watchlistHandleSet,
    }),
    content: {
      contentTab,
      setContentTab,
      createContentSource,
      onRemoveSource: () => setCreateContentSource(null),
      onSaveGeneratedArticle: handleSaveGeneratedArticle,
      onBeforeGenerate: handleBeforeGenerate,
      onBeforeRegenerate: handleBeforeRegenerate,
      isGeneratingContent,
      setIsGeneratingContent,
      genPhase,
      setGenPhase,
      searchQuery,
      setSearchQuery,
      searchMediaType,
      setSearchMediaType,
      activeSearchFocus,
      applySearchFocus: args.applySearchFocus,
      dismissSearchChoices,
      suggestions,
      showSuggestions,
      setShowSuggestions,
      activeSuggestionIndex: args.activeSuggestionIndex,
      setActiveSuggestionIndex,
      handleSearch: handlePlanSearch,
      isLatestMode,
      setIsLatestMode,
      isSearching,
      searchResults,
      searchChoiceOptions,
      setSearchResults,
      setSearchOverflowResults,
      setSearchSummary,
      setSearchWebSources,
      setSearchCursor,
      setStatus,
      shouldInlineSearchStatus,
      searchStatusMessage,
      lastSubmittedSearchQuery: args.lastSubmittedSearchQuery,
      searchPresets,
      canSaveCurrentSearchAsPreset,
      maxSearchPresets: args.maxSearchPresets,
      addSearchPreset: args.addSearchPreset,
      isLiveSearching,
      dynamicSearchTags,
      watchlistHandleSet,
      postLists,
      onAddAuthorToWatchlist: handleAddSearchAuthorToWatchlist,
      onToggleAuthorInPostList: handleToggleMemberInList,
      searchHistory,
      interestSeedLabels,
      removeSearchPreset,
      searchOverflowResults,
      searchCursor,
      searchSummary,
      searchWebSources,
      shouldShowSearchChoices,
      isSourcesExpanded,
      setIsSourcesExpanded,
      onArticleGen: openContentComposerFromPost,
      onReadArticle: openArticleReader,
      activePlanId,
    },
    pricing: {
      activePlanId,
      dailyUsage,
      remainingUsage,
      usageLimits: currentPlan.usage,
      plusAccess,
      onSelectPlan: handlePlanSelection,
      isCheckoutLoading: isStartingCheckout,
      profileSectionEventName: PROFILE_SECTION_EVENT,
    },
    read: {
      activeListId,
      currentActiveList,
      setIsMobilePostListOpen,
      readArchive,
      readSearchQuery,
      setReadSearchQuery,
      readSearchSuggestions,
      filteredReadArchive,
      readFilters,
      setReadFilters,
      visibleReadArchive,
      setVisibleReadCount,
      readArchiveRenderBatch: READ_ARCHIVE_RENDER_BATCH,
      bookmarkIds,
      handleBookmark,
      onArticleGen: openContentComposerFromPost,
      onReadArticle: openArticleReader,
    },
    audience: {
      audienceTab,
      setAudienceTab,
      aiQuery,
      setAiQuery,
      handleAiSearchAudience,
      aiSearchLoading,
      aiSearchError,
      aiSearchResults,
      aiSearchHasMore,
      setAiSearchResults,
      hasSearchedAudience,
      watchlist,
      postLists,
      handleToggleMemberInList,
      handleAddExpert,
      manualQuery,
      setManualQuery,
      showSuggestions,
      setShowSuggestions,
      activeSuggestionIndex: args.activeSuggestionIndex,
      setActiveSuggestionIndex,
      suggestions,
      handleManualSearch,
      manualPreview,
      handleAddUser: args.handleAddUser,
      handleRemoveAccountGlobal,
      subscribedSources,
      onToggleSource: handleToggleSource,
    },
    bookmarks: {
      currentActiveList,
      activeListId,
      setIsMobilePostListOpen,
      bookmarkTab,
      setBookmarkTab,
      readSearchQuery,
      setReadSearchQuery,
      filteredBookmarks,
      handleBookmark,
      onArticleGen: openContentComposerFromPost,
      onReadArticle: openArticleReader,
      setBookmarks,
    },
    profileNavigation: {
      onOpenMobileProfileDetails: () => {
        setMobileProfileSection('details');
        setActiveView('pricing');
        dispatchProfileSectionChange('details');
      },
      onOpenMobileAudience: () => {
        setActiveView('audience');
      },
    },
  };
};

export type WorkspaceRouterProps = ReturnType<typeof createWorkspaceRouterProps>;
